### PR TITLE
fix(webpack): windows compatible webpack config entry point path

### PR DESCRIPTION
**Pull request by yogesum**
- [x] I have read the [Contributing Documents](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/contributing.md)
- [x] My commit(s) follow the [AngularJS commit message guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/)
- [x] The generator's tests pass (`generator-angular-fullstack$ npm test`)

fixes (#2091)

### CODE REVIEW

**Comment by Awk34** [comment]
This Windows specific? I use a Windows box and I've never had an issue.

**Comment by Koslun** [comment]
I also have not noticed any problems on two separate Windows 10 boxes, one using one of the latest insider previews, one on the normal release cycle. Have tried doing `gulp serve` and `gulp test`. Observed that `gulp build` seemed to run but never confirmed that the output was reasonable when on Windows.

This is however the first of two PR's with this fix so I assume it's both an actual issue and a working fix. Would be interesting to know the cause for sure though.

**Comment by yogesum** [comment]
@Awk34 Yes this is window specific. work on windows 10 but not on windows 7.

**Comment by Awk34** [comment]
I have tested the code to work fine on a Win7 box. Are you sure it isn't something else wrong with your environment @yogesum ?

**Comment by yogesum** [comment]
@Awk34 With version  4.0.0-rc.0 on same windows 7 machine. working correctly.

But I think `path.join` would be good for handling path to enable cross OS compatibility.
or, You can close pull request without merge and keep in mind if issue come up again.

**Comment by Koslun** [comment]
One thing to note is that this turns the path from being a relative path to an absolute path. Where an absolute path should not just be concatenated without the `path.join` or `path.resolve`. Also explained in this [Eslint rule](http://eslint.org/docs/rules/no-path-concat).

Sending a relative path is however something that is also supported with Webpack figuring out how to concat to an absolute path on its own. As it by default uses [`process.cwd()`](https://nodejs.org/api/process.html#process_process_cwd) to determine the current working directory but can be configured by [the context variable instead](https://webpack.github.io/docs/configuration.html#context)..

As such the current entry point is a relative path and so is the example configuration featured on [webpack's homepage](https://webpack.github.io/docs/configuration.html#configuration-object-content).

So would agree on that this can be safely ignored in this instance but can be something to be kept in mind, specifically by for instance using the Eslint rule [no-path-concat](http://eslint.org/docs/rules/no-path-concat). Fortunately that's something [we're already doing](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/templates/app/.eslintrc#L131).

**Pull request closed without merging**
