### PR TITLE
chore(app): update several components

### PR DESCRIPTION
**Pull request by zeripath**
Part of #2691

- [x] I have read the [Contributing Documents](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/contributing.md)
- [x] My commit(s) follow the [AngularJS commit message guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/)
- [x] The generator's tests pass (`generator-angular-fullstack$ npm test`)

### CODE REVIEW

**Comment by zeripath** [comment]
Hmm... it looks like this one is crashing the continuous integration. Not sure quite why...

**Comment by Awk34** [comment]
I would assume this is why: https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#default-behavior

**Comment by zeripath** [comment]
Agh the mocha changes mean this is going to be slightly less simple. I guess I'll take another look tomorrow

**Comment by Awk34** [comment]
Yeah, just need to make sure the servers shut down after all the tests are complete.

I really appreciate all of the contributions!

**Comment by zeripath** [comment]
No thank you for the generator. I'm yak shaving before I actually use the generator properly.

**Comment by Awk34** [comment]
Haha 'yak shaving', that's a new one

**Comment by zeripath** [comment]
@Awk34 So I'm still having difficulty figuring out what's causing this problem. Looking at `templates/app/mocha.global.js` the testsets should close down express after every set but it seems that somehow they're not. 

I've tried sticking in delays etc. I can't even see which test is causing a restart of the express server... 

This is quite frustrating...

**Comment by Awk34** [comment]
@zeripath my assumption about what's breaking this could be wrong. Perhaps we should test with Mocha 3.5.3 to make sure it still passes, then with 4.0.0 to make sure it starts failing.

**Comment by Awk34** [comment]
If it *is* breaking because of what I think, then the proper investigation path would be to attach some debugger to be able to see what's keeping the process alive after the tests are done

**Comment by zeripath** [comment]
Ah I think I've found it.

In src/test/main.test.js:151: (amongst others)

```
before(function() {
      return runGen(null, {
        copyConfigFile: true,
        options: {
          skipInstall: true,
          skipConfig: true
        }
      }).then(_dir => {
        dir = _dir;
        lintResult = runCmd('npm run lint');
        clientTestResult = runCmd('npm run test:client');
        serverTestResult = runCmd('npm run test:server');
      });
    });
```

This causes a race somewhere in creating the express server. If these are moved out into their respective `it(...)` then the race stops happening and the crash goes away.

I haven't yet checked whether doing this changes the results of the serverTestResult... (i.e. is it still run in the correct directory.)

**Comment by Awk34** [comment]
Hmm okay, I can see that causing issues. I did this to start the test commands so that they'd run in parallel and hopefully save time. Hopefully separating the server test command won't add too much time to the test runs.

**Comment by zeripath** [comment]
Cool. It looks like I've done it! 

(The package-lock.json change that creeped in by accident has been removed too. )

**Comment by zeripath** [comment]
I think this patch might also fix issue #2746

**Pull request merged**
