### PR TITLE
feat(gulp): grunt parity

### PR DESCRIPTION
**Pull request by david-mohr**
Over the last week and a bit I've been testing and updating the gulp file (and some tests) aiming for parity with grunt.  I've merged all my changes, piece by piece, into the generator and tested the results.

More testing will be required, but hopefully this will help bring gulp support closer to release.

### CODE REVIEW

**Comment by Awk34** [comment]
squash the new task commits into something like

```
feat(gulp): add missing tasks

add tasks for x, y, z
```

**Comment by david-mohr** [comment]
Thanks @Awk34, I'll jump on these in the new few days.

**Comment by david-mohr** [comment]
Squashed and tweaked.  New PR for e2e test update is #1503

**Comment by david-mohr** [comment]
New PR for mocha test updates: #1511

**Comment by Awk34** [comment]
Thanks!!

**Pull request merged**
