### PR TITLE
fix(seed): CRSF and token issues

### LINKED ISSUE #2224: Login need to be Clicked twice. CSRF Token missing.
- [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

| Item | Version |
| --- | --- |
| generator-angular-fullstack | 3.7.5 |
| Node | 4.4.5 |
| npm | 3.9.6 |
| Operating System | Windows7 |
| yo | 1.8.4 |

| Item | Answer |
| --- | --- |
| Transpiler | Babel |
| Markup | HTML |
| CSS | SCSS |
| Router | ui-router |
| Build Tool | Gulp |
| Client Tests | Mocha |
| DB | MsSQL |
| Auth | Y |
| etc | etc |

Hey,
If I start my Project fresh it is needed to be to "Login" twice because at the first time it Errors:
Error: CSRF Token missing.
Post 403 Auth Forbidden.
After that it is working allright.
How can I change that ? Because later in Production it is not "fine" if every Customer/User has to Login himself twice.

### PR DESCRIPTION
**Pull request by daraosn**
When `express.static()` is serving `index.html` it breaks the middleware chain and avoids the CRSF to be set on `/` request, causing the first login to fail, whenever users have no cookies set.

I think this relates and possibly fixes #2224, #2511, #2611 and https://github.com/krakenjs/lusca/issues/95

This commit basically renames `_index.html` to `app.template.html` which is more expressive, and the generated file will be `app.html` which avoids `express.static()` blocking the middleware chain, because there is no `index.html` anymore. Therefore `routes.js:sendFile` is effectively called.

Note that I tried and played around A LOT with webpack trying to find another solution, this was the most elegant one I could find.

- [ ✔︎ ] I have read the [Contributing Documents](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/contributing.md)
- [ ✔︎ ] My commit(s) follow the [AngularJS commit message guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/)
- [ ✔︎ ] The generator's tests pass (`generator-angular-fullstack$ npm test`)

### CODE REVIEW

**Comment by radianz** [comment]
legend

**Comment by daraosn** [comment]
@Awk34 glad to contribute and thanks for such a nice framework!

**Comment by yeaske** [comment]
@Awk34  @daraosn  What is the best way to solve this issue for code which was built from the seed before this fix? Will the renaming of _index.html to app.template.html and changes in gulpfile.babel.js, routes.js and webpack.make.js fix this?

**Comment by Awk34** [comment]
I certainly hope so

**Comment by daraosn** [comment]
@yeaske yes, that's pretty much what needs to be done, please double check here: https://github.com/angular-fullstack/generator-angular-fullstack/pull/2613/files

**Comment by yeaske** [comment]
@Awk34 @daraosn Thanks! Worked perfectly.

**Pull request merged**
