### PR TITLE
fix(mocha): have tests clean up once complete

### PR DESCRIPTION
**Pull request by david-mohr**
mocha unit and integration tests will hang unless express (and
optionally mongoose) are closed once the tests are complete

### CODE REVIEW

**Comment by Awk34** [comment]
Hmm, looks like this isn't passing

```
1) Thing API: GET /api/things "before each" hook for "should respond with JSON array":
Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.


2) Thing API: POST /api/things "before each" hook for "should respond with the newly created thing":
Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.


3) Thing API: GET /api/things/:id "before each" hook for "should respond with the requested thing":
TypeError: Cannot read property '_id' of 
at Context.<anonymous> (server/api/thing/thing.integration.js:68:39)

4) Thing API: PUT /api/things/:id "before each" hook for "should respond with the updated thing":
TypeError: Cannot read property '_id' of undefined
at Context.<anonymous> (server/api/thing/thing.integration.js:96:39)

5) Thing API: DELETE /api/things/:id should respond with 204 on successful removal:
TypeError: Cannot read property '_id' of undefined
at Context.<anonymous> (server/api/thing/thing.integration.js:127:42)

6) Thing API: DELETE /api/things/:id should respond with 404 when thing does not exist:
TypeError: Cannot read property '_id' of undefined
at Context.<anonymous> (server/api/thing/thing.integration.js:139:42)

7) User API: "before all" hook for "should respond with 404 when thing does not exist":
Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by david-mohr** [comment]
That's weird... What options did you pick to build this test set and command did you pass to gulp?

**Comment by Awk34** [comment]
It's the generator's tests. Run `npm test` from the generator's root.

**Comment by Awk34** [comment]
I backed-out this commit and ran the tests again and they ran fine. I'm going to revert this for now.

I think what's happening is that you're closing connections after one suite of tests runs, so that the connection isn't available when the *next* suite of tests tries to run.

**Comment by david-mohr** [comment]
Leave it with me, I'll figure out why this change is failing.

**Comment by david-mohr** [comment]
I've figured out what's going on, why it's happening and a workaround. Should I submit a new PR or update this one?

**Comment by Awk34** [comment]
A new one please

**Comment by david-mohr** [comment]
New PR #1536 uses a global `after` clause and only applies to gulp

**Pull request merged**
