### PR TITLE
feat(dist:Dockerfile): initial add dist Dockerfile

### LINKED ISSUE #1531: Docker Container
I was wondering what the policy towards docker is.

There is a heroku deployer (which I use) but recently I've beed using Docker and now https://www.tutum.co/ from the dist folder. The problem as I see it is that the standard docker Node container needs a great deal of interaction when doing an `npm install` so the whole create and destroy is a bit slow. I put together a similar container which does the `npm install` ahead of time https://hub.docker.com/r/jeremymarshall/angular-fullstack-dist/

There is also a wider question of providing a mongo container and possibly using nginx as a reverse proxy ahead in a compose/tutum set

### PR DESCRIPTION
**Pull request by JeremyMarshall**
Add functionality to add Dockerfile to dist folder
in the same way as the heroku Procfile is created
No docker integration to build image

Closes #1531

### CODE REVIEW

**Comment by JeremyMarshall** [comment]
Further information

This needs a docker hub entry which I created https://hub.docker.com/r/generatorangularfullstack/angular-fullstack-dist/
which tracks on the release number (3.3.0 for the moment)
I'm happy to give control of this away. it pulls from a github repo which is just an npm install for the base dependencies - I guess these are fluid based on new releases

**Comment by Awk34** [comment]
Would it instead make more sense to just keep the Dockerfile within this repo? Then we wouldn't have any issues with versioning and dependencies.

**Comment by JeremyMarshall** [comment]
I rebuilt the dockerfile repo to https://github.com/angular-fullstack/angular-fullstack-dockerfile but I can't change the docker hub repo to https://hub.docker.com/r/generatorangularfullstack/angular-fullstack-dist/ point to it as I'm not an admin on the github repo used to build it. I added @Awk34  as an admin in hub.docker and hopefully you can fix this problem, probably by deleting and recreating the repo.

As for the dependencies, I was thinking there would be images built for every version released to avoid bit rot for apps built with older versions. This works by branching the source repo and adding it in in hub.docker https://hub.docker.com/r/generatorangularfullstack/angular-fullstack-dist/~/settings/automated-builds/

**Comment by macneib** [comment]
Referencing hub.docker.com can be problematic for several reasons.  The way I use a dockerfile is still kind of a pain to use because during automated builds the npm/bower process needs to be run once, and then npm --production needs to be run again with a dist, or something confusing like that. 

This dockerfile needs to be run from /dist after `grunt build:dist` so it needs to be copied in, and then executed as such:

`docker build -t="myAwesomeApp" .`

I usually keep a Dockerfile like this in a project repo.  

```
#
# angular-fullstack runtime Dockerfile
#

FROM alpine:latest

MAINTAINER "admin <admin@example.com>"

WORKDIR /app
ADD . /app

RUN apk update && \
    apk upgrade && \
    apk add make gcc g++ python git nodejs && rm -rf /var/cache/apk/* && \
    echo '{ "allow_root": true }' > /root/.bowerrc && \
    npm install --production && \
    apk del make gcc g++ python git && \
    rm -rf /tmp/* /var/cache/apk/* /root/.npm /root/.node-gyp

# Expose ports.
EXPOSE 8080

CMD ["npm", "start"]
```

**Comment by Awk34** [comment]
@JeremyMarshall sorry it's been so long. Do you have any time to revisit this? Perhaps respond to @macneib 's comments?

**Comment by JeremyMarshall** [comment]
You can't fault the tiny size with this approach. I think there could be room for different Dockerfiles. 
I was aiming to use the official Node Docker stack and preload the standard npm dependencies. With this it would rebuild on the docker hub infrastructure. It does need some way of keeping in step with the main generator repo though.
The changes to add the dockerfile in on their own will allow the Dockerfile to survive in the dist folder which can allow flexibility and not have to worry about re-adding the file

Possibly the approach is just to provide a standard node Dockerfile to get projects started @macneib is correct, the npm dependencies are a pain as they need to be rebuilt every time (hopefully from the cache)  unless there is an intermediate image with them pre added

**Comment by Awk34** [comment]
You can also take a look at what #938 is doing

**Comment by JeremyMarshall** [comment]
I see you closed it. I was going to put docker compose in in a separate PR
and possibly docker cloud (previously tutum)

The point about the environment is to connect node to mongo inside the
running docker using compose or docker when linking manually

**Comment by Awk34** [comment]
Well, that old PR is quite outdated, and the original author won't be updating it, that's why It'd be great if you could do that stuff as well :smile:

**Comment by Awk34** [comment]
I've given you write access, so you can make a branch directly on this repo

**Comment by JeremyMarshall** [comment]
Closed to refactor with latest changes

**Pull request closed without merging**
