### PR TITLE
Generation step added to readme.

### PR DESCRIPTION
**Pull request by gintsgints**
- [ x] I have read the [Contributing Documents](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/contributing.md)
- [ x] My commit(s) follow the [AngularJS commit message guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/)
- [ x] The generator's tests pass (`generator-angular-fullstack$ npm test`)

Probably generation step is missing in readme

### CODE REVIEW

**Comment by gintsgints** [comment]
Where you think correct place would be?

**Comment by Awk34** [comment]
You put it in the right place, but there's similar text already in the README a bit lower down the file

**Comment by gintsgints** [comment]
Ah yea... I saw it ... but it is really very confusing to have it there..

**Comment by Awk34** [comment]
Exactly, I think where you put your changes is fine, but you should also remove the `yo` section that's further down. We shouldn't duplicate it in the 'Usage' section of the README

**Comment by gintsgints** [comment]
Pls check now.

**Comment by gintsgints** [comment]
Ups.. probably I create new pull request.

**Pull request closed without merging**
