### PR TITLE
feat(gen): Generate node and Gruntfile with coffeescript

### LINKED ISSUE #92: Generate node with coffeescript
I tried to create my app with coffeescript but just the angular was generated with CS.

If I create a new .coffee file in the node's controller the file is not compiled with grunt coffee.

Did I missed something or this feature does not work?

If not I'll try to change it and make a pull request. :)

### PR DESCRIPTION
**Pull request by burtonjc**
Add build pipleline to handle coffee across whole stack

Closes #92

### CODE REVIEW

**Comment by ErikEvenson** [comment]
Would like this as well.

**Comment by rriemann** [comment]
I would like to see this integrated as well. @chester1000 , do you have an up-to-date branch with the changes you proposed for the meanwhile?

**Comment by wmertens** [comment]
How about making the server side in coffee, convert to js when required and only when the js output is unreadable provide a manual js version that is kept up-to-date manually?

I think most of the output will be ok...

**Comment by mjrk** [comment]
+1
Coffee, the yardstick of civilization.

**Comment by omgaz** [comment]
bump

**Comment by rumal** [comment]
Anything else needed to be done on this? I can help out if needed.

**Comment by harryoh** [comment]
I create new generator for server-side coffee script.
visit to https://github.com/harryoh/generator-coffee-fullstack

**Pull request closed without merging**
