### PR TITLE
Added gulp-cli to readme.md

### PR DESCRIPTION
**Pull request by javidrashid**
Added gulp-cli to readme for installation steps, since the project now supports gulp automation.

### CODE REVIEW

**Comment by Awk34** [comment]
It should be made apparent that either `grunt-cli` **or** `gulp-cli` need to be installed, depending on which you select when generating. The generated [Readme.md](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/app/templates/README.md) should also be fixed to use `gulp-cli` instead of just `gulp`.

Also make sure you conform to the [contributing guidelines](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/contributing.md)

**Comment by javidrashid** [comment]
Does it really matter if you install both gulp-cli as well as grunt-cli?

**Comment by Awk34** [comment]
No, so I'd leave the `npm install ...` line the same, but I'd change the line above to say something like "`grunt-cli` and/or `gulp-cli`".

**Comment by Awk34** [comment]
Thanks. I've updated your commits and merged.

**Pull request closed without merging**
