### PR TITLE
fix(build): fix templateCache generation on gulpfile (#1936)

### LINKED ISSUE #1936: angular-fullstack generator failed to load template while running dist folder
i am having issue regarding the template load while running dist folder with the command gulp serve:dist
The issue is random in every build.sometime it wont load the template inside components folder(directives) and sometime it won't load the template assigned to ui router states.for more detail you can see the stackoverflow issue here. [http://stackoverflow.com/questions/37498159/angular-fullstack-generator-failed-to-load-template-while-running-dist-folder](url)

### PR DESCRIPTION
**Pull request by ingoncalves**
- [x] I have read the [Contributing Documents](https://github.com/DaftMonk/generator-angular-fullstack/blob/master/contributing.md)
- [x] My commit(s) follow the [AngularJS commit message guidelines](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/)
- [x] The generator's tests pass (`generator-angular-fullstack$ npm test`)

Change execution order for gulp tasks 'transpile:client' and 'html' to fix the templateCache generation.

closes #1936

### CODE REVIEW

**Comment by Awk34** [comment]
Hmm, This fix seems strange. We don't want the `html` task to be directly dependent on the `transpile:client` task. How about instead you add `transpile:client` in the `build` task, before `build:client` gets run?

**Comment by ingoncalves** [comment]
like this?

```
gulp.task('build', cb => {
    runSequence(
        [
            'clean:dist',
            'clean:tmp'
        ],
        'jade',
        'inject',
        'wiredep:client',
        'transpile:client',
        [
            'build:images',
            'copy:extras',
            'copy:fonts',
            'copy:assets',
            'copy:server',
            'transpile:server',
            'build:client'
        ],
        cb);
});
```
it works for me!

**Comment by Awk34** [comment]
@ingoncalves precisely

**Comment by ingoncalves** [comment]
it looks more beautiful
```gulp.task('build', cb => {
    runSequence(
        [
            'clean:dist',
            'clean:tmp'
        ],
        'jade',
        'inject',
        'wiredep:client',
        [
          'transpile:client',
          'transpile:server'
        ],
        [
            'build:images',
            'copy:extras',
            'copy:fonts',
            'copy:assets',
            'copy:server',
            'build:client'
        ],
        cb);
});
```

**Pull request merged**
